### ISSUE TITLE
Requires python installed

### ISSUE THREAD

**Issue by slaFFik** [jonhoo/wp2ghost#12]
Please update the readme with the note, that the installation requires a python being installed. It's not the thing for Windows by default.

**Comment by jonhoo** [comment]
I don't think this should require Python, just NodeJS?

**Comment by slaFFik** [comment]
No, it does. It needs to compile something while installing dependencies (and down that rabbit hole) and uses python. I don't have it installed, and console errored with "python is missing" error.

**Comment by jonhoo** [comment]
Weird -- there's no such requirement for me when building on Linux, but I mentioned it anyway :)
