### ISSUE TITLE
WordPress, not Wordpress

### ISSUE THREAD

**Issue by slaFFik** [jonhoo/wp2ghost#16]
I'm sorry, but [`capital_P_dangit()`](https://codex.wordpress.org/Function_Reference/capital_P_dangit). :)

PR in a minute.

**Comment by slaFFik** [comment]
@jonhoo Could you please update the repo description too? :)
Currently, it looks like this:
> Convert Wordpress XML exports to Ghost JSON import files

**Comment by jonhoo** [comment]
Done!
