### ISSUE TITLE
 WordPress plugin wrong info

### ISSUE THREAD

**Issue by eidmantas** [jonhoo/wp2ghost#6]
Hello,

The current WordPress plugin states:
Next up spin up your Ghost installation, create a user, or sign in, if you already have an account, navigate to http://yourblogadress/ghost/debug/, and import the posts from the file.

This is not correct and should point out that you need to use 'Labs' within the admin panel.

Apart from that it still works great. Thanks.

**Comment by jonhoo** [comment]
Hello!

This script has nothing to do with the Ghost WordPress plugin. You should report the problem [there](https://wordpress.org/support/plugin/ghost). I've fixed the instructions in the README for this tool though!
